#:schema node_modules/wrangler/config-schema.json
name = "ref-finance-landing"
compatibility_date = "2024-10-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
[build]
command = "pnpm install && pnpm run build"

[env]
NODE_VERSION = "18.19.1"
